In [1]:
pip install tabula-py

Requirement already satisfied: tabula-py in /Users/mariyammukhumova/opt/anaconda3/lib/python3.8/site-packages (2.3.0)
Requirement already satisfied: distro in /Users/mariyammukhumova/opt/anaconda3/lib/python3.8/site-packages (from tabula-py) (1.6.0)
Requirement already satisfied: numpy in /Users/mariyammukhumova/opt/anaconda3/lib/python3.8/site-packages (from tabula-py) (1.20.1)
Requirement already satisfied: pandas>=0.25.3 in /Users/mariyammukhumova/opt/anaconda3/lib/python3.8/site-packages (from tabula-py) (1.2.4)
Requirement already satisfied: python-dateutil>=2.7.3 in /Users/mariyammukhumova/opt/anaconda3/lib/python3.8/site-packages (from pandas>=0.25.3->tabula-py) (2.8.1)
Requirement already satisfied: pytz>=2017.3 in /Users/mariyammukhumova/opt/anaconda3/lib/python3.8/site-packages (from pandas>=0.25.3->tabula-py) (2021.1)
Requirement already satisfied: six>=1.5 in /Users/mariyammukhumova/opt/anaconda3/lib/python3.8/site-packages (from python-dateutil>=2.7.3->pandas>=0.25.3->tabula-py) (1.15.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
pip install camelot-py

Requirement already satisfied: camelot-py in /Users/mariyammukhumova/opt/anaconda3/lib/python3.8/site-packages (0.10.1)
Requirement already satisfied: click>=6.7 in /Users/mariyammukhumova/opt/anaconda3/lib/python3.8/site-packages (from camelot-py) (7.1.2)
Requirement already satisfied: pdfminer.six>=20200726 in /Users/mariyammukhumova/opt/anaconda3/lib/python3.8/site-packages (from camelot-py) (20201018)
Requirement already satisfied: PyPDF2>=1.26.0 in /Users/mariyammukhumova/opt/anaconda3/lib/python3.8/site-packages (from camelot-py) (1.26.0)
Requirement already satisfied: pandas>=0.23.4 in /Users/mariyammukhumova/opt/anaconda3/lib/python3.8/site-packages (from camelot-py) (1.2.4)
Requirement already satisfied: openpyxl>=2.5.8 in /Users/mariyammukhumova/opt/anaconda3/lib/python3.8/site-packages (from camelot-py) (3.0.7)
Requirement already satisfied: chardet>=3.0.4 in /Users/mariyammukhumova/opt/anaconda3/lib/python3.8/site-packages (from camelot-py) (4.0.0)
Requirement already satisfied: numpy>=1.13.3 in /Users/mariyammukhumova/opt/anaconda3/lib/python3.8/site-packages (from camelot-py) (1.20.1)
Requirement already satisfied: tabulate>=0.8.9 in /Users/mariyammukhumova/opt/anaconda3/lib/python3.8/site-packages (from camelot-py) (0.8.9)
Requirement already satisfied: et-xmlfile in /Users/mariyammukhumova/opt/anaconda3/lib/python3.8/site-packages (from openpyxl>=2.5.8->camelot-py) (1.0.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /Users/mariyammukhumova/opt/anaconda3/lib/python3.8/site-packages (from pandas>=0.23.4->camelot-py) (2.8.1)
Requirement already satisfied: pytz>=2017.3 in /Users/mariyammukhumova/opt/anaconda3/lib/python3.8/site-packages (from pandas>=0.23.4->camelot-py) (2021.1)
Requirement already satisfied: sortedcontainers in /Users/mariyammukhumova/opt/anaconda3/lib/python3.8/site-packages (from pdfminer.six>=20200726->camelot-py) (2.3.0)
Requirement already satisfied: cryptography in /Users/mariyammukhumova/opt/anaconda3/lib/python3.8/site-packages (from pdfminer.six>=20200726->camelot-py) (3.4.7)
Requirement already satisfied: six>=1.5 in /Users/mariyammukhumova/opt/anaconda3/lib/python3.8/site-packages (from python-dateutil>=2.7.3->pandas>=0.23.4->camelot-py) (1.15.0)
Requirement already satisfied: cffi>=1.12 in /Users/mariyammukhumova/opt/anaconda3/lib/python3.8/site-packages (from cryptography->pdfminer.six>=20200726->camelot-py) (1.14.5)
Requirement already satisfied: pycparser in /Users/mariyammukhumova/opt/anaconda3/lib/python3.8/site-packages (from cffi>=1.12->cryptography->pdfminer.six>=20200726->camelot-py) (2.20)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import tabula

In [6]:
file1 = "/Users/mariyammukhumova/Documents/A1.pdf"

In [11]:
tables = tabula.read_pdf(file1, pages = '6', multiple_tables=False)
tables[0]

,Unnamed: 0,Unnamed: 1,SS2,SS5,SS6,SS7,SS10,SS11,SS12a,SS12b,SS14,SS15,SS18,SS19,SS20
0,NaN,NaN,(A),(A),(B),(BA),(BA),(BA),(A),(D),(A),(A),(A),(A),(A)
1,Major elements,NaN,(wt.%),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,SiO2,NaN,57.13,59.18,49.38,53.08,52.46,54.72,61.52,63.53,56.15,56.90,56.15,57.11,59.32
3,TiO2,NaN,1.15,0.96,1.79,1.59,1.68,1.24,1.01,0.77,1.22,1.32,1.43,1.02,1.12
4,Al2O3,NaN,17.41,16.97,16.81,16.65,16.72,16.74,17.03,15.53,17.44,16.65,17.51,17.15,16.44
5,Fe 2O3 âˆ—,NaN,7.16,6.17,8.94,8.62,7.65,8.52,5.26,5.68,7.59,7.16,6.37,6.77,6.13
6,MnO,NaN,0.15,0.15,0.15,0.13,0.13,0.16,0.11,0.13,0.14,0.15,0.18,0.14,0.11
7,MgO,NaN,2.95,2.69,8.45,4.95,5.51,6.38,2.05,1.47,3.91,3.51,2.84,3.13,3.07
8,CaO,NaN,5.44,5.52,7.76,6.82,7.21,5.59,4.15,3.59,5.22,5.65,5.08,5.44,4.62
9,Na2O,NaN,4.26,4.17,3.51,4.12,4.32,3.45,4.48,4.37,4.03,4.22,4.47,4.69,4.76
10,K2O,NaN,1.97,2.14,1.15,1.25,1.79,1.38,3.16,3.16,2.45,2.82,2.39,2.54,2.85
11,P2O5,NaN,0.24,0.28,0.27,0.35,0.43,0.21,0.20,0.12,0.21,0.35,0.35,0.27,0.19
12,LOI,NaN,1.64,1.41,1.65,2.25,1.41,1.45,0.82,0.70,1.55,1.16,2.10,1.52,0.76
13,Sum,NaN,99.50,99.64,99.86,99.81,99.31,99.84,99.79,99.05,99.91,99.89,98.87,99.78,99.37
14,Mg#,NaN,45,46,65,53,59,60,44,34,51,49,47,48,50
15,Na2O + K2O,NaN,6.23,6.31,4.66,5.37,6.11,4.83,7.64,7.53,6.48,7.04,6.86,7.23,7.61
16,Na2O/K2O,NaN,2.16,1.95,3.05,3.30,2.41,2.50,1.42,1.38,1.64,1.50,1.87,1.85,1.67
17,FeOâˆ—/MgO,NaN,2.18,2.06,0.95,1.57,1.25,1.20,2.31,3.48,1.75,1.84,2.02,1.95,1.80
18,Trace elements,NaN,(ppm),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Cr,NaN,124,157,250,215,128,254,56,10,120,183,90,150,106
20,Ni,NaN,47,66,180,126,96,112,15,4,55,50,73,39,71
21,Co,NaN,22,23,35,27,31,38,17,11,30,28,29,21,20
22,V,NaN,190,135,280,265,250,242,166,150,215,140,103,127,178
23,Pb,NaN,17,21,18,14,15,17,19,28,19,18,15,18,20
24,Zn,NaN,17,21,18,14,15,17,62,110,19,18,15,18,85
25,Rb,NaN,65,51,32,35,45,37,76,85,62,72,54,67,64
26,Ba,NaN,678,914,602,543,643,711,712,868,771,715,940,551,654
27,Sr,NaN,690,773,940,745,791,620,415,385,930,892,810,363,335
28,Nb,NaN,10,8,5,7,8,4,8,15,5,5,8,11,9
29,Zr,NaN,195,190,157,203,190,153,240,308,145,230,227,160,285
30,Y,NaN,21,20,19,20,26,18,29,35,22,21,19,24,27
31,Th,NaN,5,6,4,4,3,5,6,6,8,5,6,4,5
32,U,NaN,2,nd,2,2,2,2,3,4,2,2,2,nd,3
33,Zr/Y,NaN,9,10,8,10,7,9,8,9,7,11,12,7,11
34,K/Rb,NaN,252,348,298,296,330,310,345,309,328,325,367,315,370
35,Rb/Sr,NaN,0.06,0.07,0.05,0.05,0.06,0.06,0.18,0.22,0.04,0.04,0.05,0.16,0.15
36,Rb/Ba,NaN,0.06,0.06,0.08,0.06,0.07,0.05,0.11,0.10,0.05,0.05,0.04,0.11,0.07

In [28]:
tables[0].to_csv('file.csv', index = False)

In [5]:
import camelot

In [10]:
import os
os.path.abspath("/Users/mariyammukhumova/Documents/")
from tabula import wrapper
tables = wrapper.read_pdf("A1.pdf",multiple_tables=True,pages='all')

i=1
for table in tables:
    table.to_excel('output'+str(i)+'.xlsx',index=False)
    print(i)
    i=i+1

ImportError: cannot import name 'wrapper' from 'tabula' (/Users/mariyammukhumova/opt/anaconda3/lib/python3.8/site-packages/tabula/__init__.py)